### ISSUE TITLE
Tree trimming bug URGENT

### ISSUE THREAD

**Issue by rbibbs** [syntax-prosody-ot/main#310]
Using the tree trimming with clitics results in an uxpected relabeling (or pruning problem) involved with the clitics.

Example:  

[[a [b]]   **[x.clitic]**] 

trimmed: [[a [b]] **dp.xp**]

We want the XP phrase boundaries around the clitic to be maintained through the trimming.
Might be caused by the "clitic" label on the XP in the input syntax, not really sure...

**Comment by maxTarlov** [comment]
If you switch to the sCat_conflation_interface branch and build your problem should be solved. I forgot that "clitic" was a terminal category that I needed to worry about. Are there any other categories (other than x0 and clitic) that we don't want to trim when they don't have children?

**Comment by rbibbs** [comment]
Hmmm, I'm not sure if I'm doing something incorrectly, but I went to the sCat_conflation_interface branch, built, and still have the same issue.

**Comment by maxTarlov** [comment]
Interesting. It is working fine for me. The only possible issue that I can think of is that maybe you are in the sCat_conflation branch, not the sCat_conflation_interface branch (I had to make another branch to be able to fix some merge conflicts). I merged sCat_conflation_interface into sCat_conflation just to be safe, so if it still doesn't work, can you email me line 56 of treeTrimming.js?

**Comment by rbibbs** [comment]
Ah, you're completely right, that is exactly what was wrong. My mistake! Either way, it works great now, thank you Max!
